"""initial schema

Revision ID: 8e7b7f0ea28f
Revises: 
Create Date: 2026-04-13 21:58:45.528269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7b7f0ea28f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_user',
    sa.Column('user_id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('c_user', schema=None) as batch_op:
        batch_op.create_index('idx_user_search', ['name', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_c_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_c_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_c_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_c_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_c_user_phone_number'), ['phone_number'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index('idx_email_created', ['email', 'created_at'], unique=False)
        batch_op.create_index('idx_status_type', ['status', 'message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_status'), ['status'], unique=False)

    op.create_table('movies',
    sa.Column('movie_id', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=250), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index('idx_movie_search', ['title', 'genre', 'language'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_title'), ['title'], unique=False)

    op.create_table('partnership_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_email', sa.String(length=300), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('brand_name', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('num_theaters', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_email', 'brand_name', name='uq_owner_brand')
    )
    with op.batch_alter_table('partnership_requests', schema=None) as batch_op:
        batch_op.create_index('idx_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_owner_phone'), ['owner_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnership_requests_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_role_name'), ['role_name'], unique=True)

    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['c_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_appuser_user')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index('idx_role_active', ['role_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('movie_id', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['c_user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_movie_review_date', ['movie_id', 'review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('theater_brands',
    sa.Column('brand_id', sa.String(length=300), nullable=False),
    sa.Column('brand_name', sa.String(length=250), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('brand_id')
    )
    with op.batch_alter_table('theater_brands', schema=None) as batch_op:
        batch_op.create_index('idx_owner_brand', ['owner_id', 'brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_theater_brands_brand_name'), ['brand_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_theater_brands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_theater_brands_owner_id'), ['owner_id'], unique=False)

    op.create_table('theaters',
    sa.Column('theater_id', sa.String(length=300), nullable=False),
    sa.Column('brand_id', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['theater_brands.brand_id'], ),
    sa.PrimaryKeyConstraint('theater_id')
    )
    with op.batch_alter_table('theaters', schema=None) as batch_op:
        batch_op.create_index('idx_brand_city', ['brand_id', 'city'], unique=False)
        batch_op.create_index('idx_state_city', ['state', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_theaters_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_theaters_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_theaters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_theaters_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_theaters_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_theaters_state'), ['state'], unique=False)

    op.create_table('screens',
    sa.Column('screen_id', sa.String(length=300), nullable=False),
    sa.Column('theater_id', sa.String(length=300), nullable=True),
    sa.Column('screen_number', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.theater_id'], ),
    sa.PrimaryKeyConstraint('screen_id'),
    sa.UniqueConstraint('theater_id', 'screen_number', name='uq_theater_screen')
    )
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.create_index('idx_theater_screen', ['theater_id', 'screen_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_screens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_screens_screen_number'), ['screen_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_screens_theater_id'), ['theater_id'], unique=False)

    op.create_table('shows',
    sa.Column('show_id', sa.String(length=300), nullable=False),
    sa.Column('movie_id', sa.String(length=300), nullable=True),
    sa.Column('theater_id', sa.String(length=300), nullable=True),
    sa.Column('screen_id', sa.String(length=300), nullable=True),
    sa.Column('show_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.screen_id'], ),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.theater_id'], ),
    sa.PrimaryKeyConstraint('show_id')
    )
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_index('idx_movie_date', ['movie_id', 'show_date'], unique=False)
        batch_op.create_index('idx_movie_status', ['movie_id', 'status'], unique=False)
        batch_op.create_index('idx_theater_date', ['theater_id', 'show_date'], unique=False)
        batch_op.create_index('idx_theater_status', ['theater_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_screen_id'), ['screen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_show_date'), ['show_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_theater_id'), ['theater_id'], unique=False)

    op.create_table('bookings',
    sa.Column('booking_id', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('show_id', sa.String(length=300), nullable=True),
    sa.Column('booking_date', sa.DateTime(), nullable=True),
    sa.Column('total_tickets', sa.Integer(), nullable=True),
    sa.Column('seat_numbers', sa.String(length=500), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=200), nullable=True),
    sa.Column('transaction_ref', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['c_user.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('idx_show_booking_date', ['show_id', 'booking_date'], unique=False)
        batch_op.create_index('idx_status_booking_date', ['payment_status', 'booking_date'], unique=False)
        batch_op.create_index('idx_user_booking_date', ['user_id', 'booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_show_id'), ['show_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_transaction_ref'), ['transaction_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=300), nullable=False),
    sa.Column('booking_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=200), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('transaction_ref', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['c_user.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_status_payment_date', ['status', 'payment_date'], unique=False)
        batch_op.create_index('idx_user_payment_date', ['user_id', 'payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_ref'), ['transaction_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('seats',
    sa.Column('seat_id', sa.String(length=300), nullable=False),
    sa.Column('screen_id', sa.String(length=300), nullable=True),
    sa.Column('seat_number', sa.String(length=200), nullable=True),
    sa.Column('seat_type', sa.String(length=200), nullable=True),
    sa.Column('charger', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('show_id', sa.String(length=300), nullable=True),
    sa.Column('booking_id', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.screen_id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('screen_id', 'seat_number', name='uq_screen_seat')
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index('idx_booking_seat', ['booking_id', 'seat_number'], unique=False)
        batch_op.create_index('idx_screen_show', ['screen_id', 'show_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_screen_id'), ['screen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_seat_number'), ['seat_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_seat_type'), ['seat_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_show_id'), ['show_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_status'))
        batch_op.drop_index(batch_op.f('ix_seats_show_id'))
        batch_op.drop_index(batch_op.f('ix_seats_seat_type'))
        batch_op.drop_index(batch_op.f('ix_seats_seat_number'))
        batch_op.drop_index(batch_op.f('ix_seats_screen_id'))
        batch_op.drop_index(batch_op.f('ix_seats_created_at'))
        batch_op.drop_index(batch_op.f('ix_seats_booking_id'))
        batch_op.drop_index('idx_screen_show')
        batch_op.drop_index('idx_booking_seat')

    op.drop_table('seats')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_transaction_ref'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_method'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_booking_id'))
        batch_op.drop_index('idx_user_payment_date')
        batch_op.drop_index('idx_status_payment_date')

    op.drop_table('payments')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_transaction_ref'))
        batch_op.drop_index(batch_op.f('ix_bookings_show_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_payment_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_date'))
        batch_op.drop_index('idx_user_booking_date')
        batch_op.drop_index('idx_status_booking_date')
        batch_op.drop_index('idx_show_booking_date')

    op.drop_table('bookings')
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shows_theater_id'))
        batch_op.drop_index(batch_op.f('ix_shows_status'))
        batch_op.drop_index(batch_op.f('ix_shows_start_time'))
        batch_op.drop_index(batch_op.f('ix_shows_show_date'))
        batch_op.drop_index(batch_op.f('ix_shows_screen_id'))
        batch_op.drop_index(batch_op.f('ix_shows_movie_id'))
        batch_op.drop_index(batch_op.f('ix_shows_created_at'))
        batch_op.drop_index('idx_theater_status')
        batch_op.drop_index('idx_theater_date')
        batch_op.drop_index('idx_movie_status')
        batch_op.drop_index('idx_movie_date')

    op.drop_table('shows')
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screens_theater_id'))
        batch_op.drop_index(batch_op.f('ix_screens_screen_number'))
        batch_op.drop_index(batch_op.f('ix_screens_created_at'))
        batch_op.drop_index('idx_theater_screen')

    op.drop_table('screens')
    with op.batch_alter_table('theaters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theaters_state'))
        batch_op.drop_index(batch_op.f('ix_theaters_name'))
        batch_op.drop_index(batch_op.f('ix_theaters_location'))
        batch_op.drop_index(batch_op.f('ix_theaters_created_at'))
        batch_op.drop_index(batch_op.f('ix_theaters_city'))
        batch_op.drop_index(batch_op.f('ix_theaters_brand_id'))
        batch_op.drop_index('idx_state_city')
        batch_op.drop_index('idx_brand_city')

    op.drop_table('theaters')
    with op.batch_alter_table('theater_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theater_brands_owner_id'))
        batch_op.drop_index(batch_op.f('ix_theater_brands_created_at'))
        batch_op.drop_index(batch_op.f('ix_theater_brands_brand_name'))
        batch_op.drop_index('idx_owner_brand')

    op.drop_table('theater_brands')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_review_date'))
        batch_op.drop_index(batch_op.f('ix_reviews_rating'))
        batch_op.drop_index(batch_op.f('ix_reviews_movie_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))
        batch_op.drop_index('idx_movie_review_date')

    op.drop_table('reviews')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_app_users_name'))
        batch_op.drop_index(batch_op.f('ix_app_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_app_users_email'))
        batch_op.drop_index(batch_op.f('ix_app_users_created_at'))
        batch_op.drop_index('idx_role_active')

    op.drop_table('app_users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_name'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('partnership_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnership_requests_status'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_state'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_owner_phone'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_owner_name'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_owner_email'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_city'))
        batch_op.drop_index(batch_op.f('ix_partnership_requests_brand_name'))
        batch_op.drop_index('idx_status_created')

    op.drop_table('partnership_requests')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_title'))
        batch_op.drop_index(batch_op.f('ix_movies_status'))
        batch_op.drop_index(batch_op.f('ix_movies_release_date'))
        batch_op.drop_index(batch_op.f('ix_movies_rating'))
        batch_op.drop_index(batch_op.f('ix_movies_language'))
        batch_op.drop_index(batch_op.f('ix_movies_is_featured'))
        batch_op.drop_index(batch_op.f('ix_movies_genre'))
        batch_op.drop_index(batch_op.f('ix_movies_created_at'))
        batch_op.drop_index('idx_movie_search')

    op.drop_table('movies')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_status'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_name'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_email'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))
        batch_op.drop_index('idx_status_type')
        batch_op.drop_index('idx_email_created')

    op.drop_table('contact_messages')
    with op.batch_alter_table('c_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_c_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_c_user_name'))
        batch_op.drop_index(batch_op.f('ix_c_user_is_active'))
        batch_op.drop_index(batch_op.f('ix_c_user_email'))
        batch_op.drop_index(batch_op.f('ix_c_user_created_at'))
        batch_op.drop_index('idx_user_search')

    op.drop_table('c_user')
    # ### end Alembic commands ###